name: Jeu Vidéo II Hizq
favicon: null
layout_spectrum: 0.5716846
typography_spectrum: 0.5394265
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Jeu Vidéo II Hizq
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4833884742110968
  lightness: 0.0123354708775878
  saturation: 0.424465558025986
  rhythmicContrast: 0.04654259630478919
purpose: []
