name: Jeu Vidéo II Hizq
favicon: null
layout_spectrum: 0.029953267658129334
typography_spectrum: 0.5434089151676744
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.48338847421109676
  lightness: 0.012335470877587795
  saturation: 0.42446555802598596
  rhythmicContrast: 0.046542596304789186
purpose: []
