title: Jeu Vidéo II Hizq
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6971326
  brandStrength: 0.1875
  lightness: 0.6129032
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  rhythmicContrast: 0.6200717
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Jeu Vidéo II Hizq
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5394265
layout_spectrum: 0.3456998
